// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPrs-us9SBypJCCb50X3moWfi1yGQwuj8',
    appId: '1:314218537893:web:3b92117cf9479bd3507e4c',
    messagingSenderId: '314218537893',
    projectId: 'web-shop-c01fa',
    authDomain: 'web-shop-c01fa.firebaseapp.com',
    storageBucket: 'web-shop-c01fa.appspot.com',
    measurementId: 'G-XDMGWT46J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoBC1jY5ZpHLVY4ajAF7Ze9hPGc11lYZA',
    appId: '1:314218537893:android:696dfebe647880ee507e4c',
    messagingSenderId: '314218537893',
    projectId: 'web-shop-c01fa',
    storageBucket: 'web-shop-c01fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx_Mb2jVzM3tgbbAd2FA5E-sW-SP0sOl4',
    appId: '1:314218537893:ios:049b357366f6ec40507e4c',
    messagingSenderId: '314218537893',
    projectId: 'web-shop-c01fa',
    storageBucket: 'web-shop-c01fa.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx_Mb2jVzM3tgbbAd2FA5E-sW-SP0sOl4',
    appId: '1:314218537893:ios:049b357366f6ec40507e4c',
    messagingSenderId: '314218537893',
    projectId: 'web-shop-c01fa',
    storageBucket: 'web-shop-c01fa.appspot.com',
    iosBundleId: 'com.example.myApp',
  );
}
